### PR TITLE
add wie_after_widget_import action

### PR DESCRIPTION
**Pull request by miljan-aleksic**
As discussed in #6

### CODE REVIEW

**Comment by stevengliebe** [comment]
Thanks, I'll give this attention next week.

**Comment by stevengliebe** [comment]
This was merged into 1.2.2, released today.

**Comment by miljan-aleksic** [comment]
Nice :) tks

**Comment by stevengliebe** [comment]
You're welcome and thank you! :)

**Comment by stevengliebe** [comment]
Do you have a WordPress.org username? I'm adding contributors to the credits there. Please send yours if you'd like to be included. Thank you.

**Pull request merged**
